config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "items#index"

  resources :items do
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end
  resources :users, only: [:show, :edit, :update, :destroy]
end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :user

  has_many :photos, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true, length: {maximum: 100}
  validates :address, presence: true
  validates :description, presence: true, length: {maximum: 500}

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :item
  belongs_to :user

  validates :item, presence: true
  validates :user, presence: true
  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader

  scope :persisted, -> { where "id IS NOT NULL" }
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :items, dependent: :destroy

  validates :name, presence: true, length: {maximum: 35}

  before_validation :set_name, on: :create

  mount_uploader :avatar, AvatarUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
    end
  end

  private

  # задаем юзеру случайное имя, если оно пустое
  def set_name
    self.name = "Меняла №#{rand(777)}" if self.name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  # хелпер метод, доступный во вьюхах
  helper_method :current_user_can_edit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u|
      u.permit(:name, :address, :phone, :avatar, :email, :password, :password_confirmation)
    }
    devise_parameter_sanitizer.for(:account_update) { |u|
      u.permit(:password, :password_confirmation, :current_password)
    }
  end

  # показывает может ли текущий залогиненный юзер править эту модель
  def current_user_can_edit?(model)
    user_signed_in? &&
        (model.user == current_user || # если у модели есть юзер и он залогиненный
            (model.try(:item).present? && model.item.user == current_user))
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_item, only: [:show]
  before_action :set_current_user_item, only: [:edit, :update, :destroy]
  # GET /items
  def index
    @items = Item.all
    @items = Item.paginate(page: params[:page], per_page: 18).order(created_at: :desc)
  end

  # GET /items/1
  def show
    @new_photo = @item.photos.build(params[:photo])
  end

  # GET /items/new
  def new
    @item = current_user.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = current_user.items.build(item_params)

    if @item.save
      redirect_to @item, notice: I18n.t('controllers.items.created')
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: I18n.t('controllers.items.updated')
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: I18n.t('controllers.items.destroyed')
  end

  private

  def set_current_user_item
    @item = current_user.items.find(params[:id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :address, :description, :page)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_item, only: [:create, :destroy]

  before_action :set_photo, only: [:destroy]

  def create
    @new_photo = @item.photos.build(photo_params)
    @new_photo.user = current_user

    if @new_photo.save
      redirect_to @item, notice: I18n.t('controllers.photos.created')
    else
      render 'items/show', alert: I18n.t('controllers.photos.error')
    end
  end

  def destroy
    message = {notice: I18n.t('controllers.photos.destroyed')}

    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      message = {alert: I18n.t('controllers.photos.error')}
    end

    redirect_to @item, message
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user, except: [:show]

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, :email, :phone, :address, :avatar, :destroy)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar?
      user.avatar.url
    else
      asset_path('user.png')
    end
  end

  def user_avatar_thumb(user)
    if user.avatar.file.present?
      user.avatar.thumb.url
    else
      asset_path('user.png')
    end
  end

  def item_photo(item)
    photos = item.photos.persisted

    if photos.any?
      photos.sample.photo.url
    else
      asset_path('item.jpg')
    end
  end

  def item_thumb(item)
    photos = item.photos.persisted

    if photos.any?
      photos.sample.photo.url
    else
      asset_path('item.jpg')
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
   <div class="alert alert-danger alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>#{sentence}</h4>
    #{messages}
   </div>
    HTML

    html.html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
    <%= render partial: 'partials/form_errors', locals: {model: @item} %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
    </div>
<% end %>

app/views/items/_item.html.erb
<div class="col-sm-12 col-sm-2">
  <h4 class="title-i"><%= link_to item.title, item_path(item) %></h4>
  <div class="thumbnail">
    <a href="<%= item_path(item) %>">
      <%= image_tag item_thumb(item), alt: "item_jpg", id: "HomeImage" %>
    </a>
  </div>
  <div class="thumbnail-inner item-info-inner">
    <div class="item-description">
      <div class="buffer-both text-left">
        <div class='fa fa-map-marker text-address'>
          &nbsp;|&nbsp;<%= item.address %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<h1>Редактирование товара</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/items/index.html.erb
<div class="text-center">
  <div class="buffer-both"></div>
  <div class="row buffer-bottom">
    <%= render partial: 'items/item', collection: @items %>
  </div>
  <div class="apple_pagination">
    <div class="text-left "><%= will_paginate @item, class: 'text-center' %>&copy; Sergey Drach 2016</div>
  </div>
</div>

app/views/items/new.html.erb
<h1>Товар на обмен</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/items/show.html.erb
<div class="item">
  <div class="item-info row">
    <div class="col-md-8">
      <h2 class="page-header"><%= @item.title %></h2>
      <h3><div class='fa fa-map-marker space'></div><%= @item.address %></h3>
      <div class="img-rounded"><%= image_tag(item_photo(@item), class: 'img-thumbnail') %>
      </div>
      <div class="item-photos">
        <%# Выводим все фотографии товара %>
        <div class="item-photos-gallery">
          <%= render partial: 'photos/photo', collection: @item.photos.except(@new_photo) %>
        </div>
        <%# Кнопка вывода формы добавления фотографии %>
        <%# Рисуем форму для добавления новой фотографии (которая будет скрыта) %>
      </div>

      <div class="buffer-top">
        <% if current_user_can_edit?(@item) %>
            <div class="item-photo-form">
              <%= render partial: 'photos/form', locals: {photo: @new_photo || @item.photos.build} %>
            </div>
            <p class="text-center">
              <%= link_to 'Удалить товар', item_path(@item), method: :delete, class: 'btn btn-sm btn-danger',
                          data: {confirm: "Вы уверены?"} %>
              <%= link_to 'Изменить описание', edit_item_path(@item), class: 'btn btn-sm btn-warning' %>
            </p>
        <% end %>
      </div>

      <div class="row">
        <div class="col-md-8">
          <div class="panel panel-default">
            <div class="panel-heading">Описание</div>
            <div class="panel-body">
              <p><%= @item.description %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <h4>Предлагает обмен:</h4>
      <h3><%= render partial: 'users/user', object: @item.user %></h3>
      <table class="table table-striped">
        <tr>
          <th>
            <div class="fa fa-home space"></div>
            Адрес</th>
          <td><%= @item.user.address %></td>
        </tr>
        <tr>
          <th>
            <div class="fa fa-phone space"></div>
            Телефон</th>
          <td><%= @item.user.phone %></td>
        </tr>
        <tr>
          <th>
            <div class="fa fa-envelope space"></div>
            Email</th>
          <td><%= @item.user.email %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "МоеТвое" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/4.0.1/ekko-lightbox.min.css", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/4.0.1/ekko-lightbox.min.js" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"
          type="text/javascript"></script>
  <![endif]-->
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <%= link_to "Moe Tvoe", root_path, class: 'navbar-brand' %>
    <%= image_tag "logo_200.jpg", alt: "swap_img",
                  id: "HomeImage",
                  class: "img-circle img-logo" %>
    <%= link_to ' Хочу меняться', new_item_path, class: 'text-center  btn btn-success navbar-btn fa fa-exchange' %>
    <ul class="navbar-right">
      <% if user_signed_in? %>
          <%= link_to ' Профиль', current_user, class: 'btn btn-default navbar-btn fa fa-user' %>
          <%= link_to ' Выйти', destroy_user_session_path, class: 'btn btn-default navbar-btn fa fa-sign-out', :method => :delete %>
      <% else %>
          <%= link_to ' Войти', new_user_session_path, class: 'btn btn-default navbar-btn fa fa-sign-in' %>
          <%= link_to ' Зарегистрироваться', new_user_registration_path, class: 'btn btn-danger navbar-btn fa fa-plug' %>
      <% end %>
    </ul>
  </div>
  </div>
</nav>

<div class="container">
  <div class=".row-fluid">
    <div class="col-xs-12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
</div> <!-- /container -->
</body>
</html>

app/views/partials/_form_errors.html.erb
<!-- Универсальный паршиал отображения ошибок валидации любой модели -->

<% errors = model.errors %>

<% if errors.any? %>
    <div class="alert alert-danger">
      <div class="lead buffer-bottom">
        В вашей форме <%= errors.count %>&nbsp;<%= Russian::pluralize(errors.count, 'ошибка', 'ошибки', 'ошибок') %>
      </div>
      <ul>
        <% errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/photos/_form.html.erb
<%= form_for [@item, photo], html: {multipart: true} do |f| %>
    <%= render partial: 'partials/form_errors', locals: {model: photo} %>

    <div class="form-group">
      <%= f.label :photo %>
      <%= f.file_field :photo %>
    </div>

    <div class="actions">
      <%= f.submit 'Добавить фотку', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/photos/_photo.html.erb
<% image_title = "Добавил #{render partial: 'users/user', object: photo.user}" %>

<% if current_user_can_edit?(photo) %>
    <% image_title += link_to(
        fa_icon('trash'), item_photo_path(photo.item, photo),
        method: :delete, data: {confirm: t('.destroy_confirm')}
    ) %>
<% end %>

<span class="item-photo">
  <%= link_to image_tag(photo.photo.thumb.url), photo.photo.url, data: {
      toggle: 'lightbox', title: image_title, gallery: 'item-photos'
  } %>
</span>

app/views/users/_form.html.erb
<%= form_for @user, html: {multipart: true} do |f| %>

    <%= render partial: 'partials/form_errors', locals: {model: @user} %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, autofocus: true, class: "form-control", placeholder: "Ваш адрес" %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :avatar %>
      <p><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
      <%= f.file_field :avatar %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <% if @minimum_password_length %>
          <em class="buffer-left">(<%= @minimum_password_length %> символов минимум)</em>
      <% end %>
      <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Пароль" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "Повторный пароль" %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
    </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag(user_avatar(user), class: 'img-icon') %>
  </span>
  <span class="user-name">
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<h1>Редактирование профиля</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>

    <p class="buffer-top">
      <!-- Ссылка на смену пароля текущего залогиненного юзера (этот путь генерит девайз) -->
      <%= link_to 'Сменить пароль', edit_user_registration_path %>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6">
    <%= image_tag user_avatar(@user) %>
  </div>
  <div class="col-md-6">
    <h2>Профиль менялы</h2>
    <table class="table table-striped">
      <tbody>
      <tr>
        <th>
          <div class="fa fa-user space"></div>
          Имя
        </th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>
          <div class="fa fa-home space"></div>
          Адрес
        </th>
        <td><%= @user.address %></td>
      </tr>
      <tr>
        <th>
          <div class="fa fa-phone space"></div>
          Телефон
        </th>
        <td><%= @user.phone %></td>
      </tr>
      <tr>
        <th>
          <div class="fa fa-envelope space"></div>
          Email
        </th>
        <td><%= @user.email %></td>
      </tr>
      </tbody>
    </table>
    <% if @user == current_user %>
        <p class="buffer-top">
          <%= link_to 'Редактировать профиль', edit_user_path(@user), class: 'btn btn-warning' %>
          <%= link_to 'Удалить профиль', registration_path(@user), data: {confirm: "Удалить профиль?"}, method: :delete,
                      class: 'btn btn-sm btn-danger', data: {confirm: "Вы уверены?"} %>
        </p>
    <% end %>
  </div>
</div>

<%# Выводим список товаров пользователя %>
<div class="row">
  <div class="col-md-12">
    <% if @user.items.any? %>
        <h3>Меняет:</h3>
        <div class="row">
          <%= render partial: 'items/item', collection: @user.items %>
        </div>
    <% else %>
        <p class="buffer-top">Пользователь пока ничего не меняет</p>
    <% end %>
  </div>
</div>